version: "2.3"

services:
    postgres:
        container_name: service-postgres
        image: postgres:12
        environment: &db_env
          POSTGRES_DB: order_processing_db_1
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432
        volumes:
          - ./postgresql/schemas:/docker-entrypoint-initdb.d
        networks:
          - postgres

    order_processing-container:
        image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
        privileged: true
        environment:
          <<: *db_env
          PREFIX: ${PREFIX:-~/.local}
          CCACHE_DIR: /order_processing/.ccache
          CORES_DIR: /cores
        volumes:
          - .:/order_processing:rw
          - ${TC_CORES_DIR:-./.cores}:/cores:rw
        ports:
          - 8080:8080
        working_dir: /order_processing
        entrypoint:
          - ./tests/run_as_user.sh
        depends_on:
          - postgres
        networks:
          - postgres

networks:
    postgres:
        driver: bridge
